export const SPEECH = {
  INFO_MODAL: {
    INFORMATION: "common.INFORMATION",   

    LANGUAGE_AND_NOTICES: "common.LANGUAGE_AND_NOTICES",
    LANGUAGE_NOTICES_DESC: "common.LANGUAGE_NOTICES_DESC",

    DATE_TIME_FLOOR: "common.DATE_TIME_FLOOR",
    DATE_TIME_FLOOR_DESC: "common.DATE_TIME_FLOOR_DESC",

    LOGIN_METHODS: "common.LOGIN_METHODS",
    LOGIN_METHODS_DESC: "common.LOGIN_METHODS_DESC",

    NAVIGATION_BOOKING: "common.NAVIGATION_BOOKING",
    NAVIGATION_BOOKING_DESC: "common.NAVIGATION_BOOKING_DESC",

    FOOTER_TOOLS: "common.FOOTER_TOOLS",
    FOOTER_TOOLS_DESC: "common.FOOTER_TOOLS_DESC",

    BOOKING_POPUPS: "common.BOOKING_POPUPS",
    BOOKING_POPUPS_DESC: "common.BOOKING_POPUPS_DESC",

    GATE_CONFIRMATION: "common.GATE_CONFIRMATION",
    GATE_CONFIRMATION_DESC: "common.GATE_CONFIRMATION_DESC",

    GROUP_ROOM_BOOKING: "common.GROUP_ROOM_BOOKING",
    GROUP_ROOM_BOOKING_DESC: "common.GROUP_ROOM_BOOKING_DESC",

    MULTIPLE_BOOKING: "common.MULTIPLE_BOOKING",
    MULTIPLE_BOOKING_DESC: "common.MULTIPLE_BOOKING_DESC",
  }
};
