export const SPEECH = {
  INFO_MODAL: {
    INFORMATION: "speech.INFORMATION",   

    LANGUAGE_AND_NOTICES: "speech.LANGUAGE_AND_NOTICES",
    LANGUAGE_NOTICES_DESC: "speech.LANGUAGE_NOTICES_DESC",

    DATE_TIME_FLOOR: "speech.DATE_TIME_FLOOR",
    DATE_TIME_FLOOR_DESC: "speech.DATE_TIME_FLOOR_DESC",

    LOGIN_METHODS: "speech.LOGIN_METHODS",
    LOGIN_METHODS_DESC: "speech.LOGIN_METHODS_DESC",

    NAVIGATION_BOOKING: "speech.NAVIGATION_BOOKING",
    NAVIGATION_BOOKING_DESC: "speech.NAVIGATION_BOOKING_DESC",

    FOOTER_TOOLS: "speech.FOOTER_TOOLS",
    FOOTER_TOOLS_DESC: "speech.FOOTER_TOOLS_DESC",

    BOOKING_POPUPS: "speech.BOOKING_POPUPS",
    BOOKING_POPUPS_DESC: "speech.BOOKING_POPUPS_DESC",

    GATE_CONFIRMATION: "speech.GATE_CONFIRMATION",
    GATE_CONFIRMATION_DESC: "speech.GATE_CONFIRMATION_DESC",

    GROUP_ROOM_BOOKING: "speech.GROUP_ROOM_BOOKING",
    GROUP_ROOM_BOOKING_DESC: "speech.GROUP_ROOM_BOOKING_DESC",

    MULTIPLE_BOOKING: "speech.MULTIPLE_BOOKING",
    MULTIPLE_BOOKING_DESC: "speech.MULTIPLE_BOOKING_DESC",
  }
};
