export const DEFAULT_VALUES = {
  MINIMUM_SCALE_MULTIPLIER: 1,
  ZOOM_AFTER_SCALE: 1.5,
  USE_SEAT_BOUNDS: true,
  SEAT_BOUNDS_MARGIN: 50,

  USE_LEGACY_SYSTEM_MAPPING: false,
  USE_LEGACY_SYSTEM_MAPPING_WIDTH: 3800,
  USE_LEGACY_SYSTEM_MAPPING_HEIGHT: 3300,

  MINIMAP_SCALE_FACTOR: 0.08,
  MINIMAP_POSITION_TOP: 12, // Default top position
  MINIMAP_POSITION_LEFT: 12, // This is now RIGHT position (distance from right edge)
  SEAT_OVERLAP_THRESHOLD: 0.1,
};

export const ROOM_WISE_CONFIG = {
  16101: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 80,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.01,
  },

  16301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 120,
    MINIMAP_SCALE_FACTOR: 0.06,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17201: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 100,
    MINIMAP_SCALE_FACTOR: 0.06,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17202: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 70,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17101: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 90,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 110,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18201: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 95,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18202: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 75,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18101: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 85,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 105,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },
};

export function getRoomConfig(roomId) {
  const roomSpecificConfig = ROOM_WISE_CONFIG[roomId] || {};
  return {
    ...DEFAULT_VALUES,
    ...roomSpecificConfig,
  };
}
