export const DEFAULT_VALUES = {
  MINIMUM_SCALE_MULTIPLIER: 1,
  ZOOM_SEATS_SCALE: 1,
  ZOOM_AFTER_SCALE: 1.5,
  USE_SEAT_BOUNDS: true,
  SEAT_BOUNDS_MARGIN: 50,

  USE_LEGACY_SYSTEM_MAPPING: false,
  USE_LEGACY_SYSTEM_MAPPING_WIDTH: 3800,
  USE_LEGACY_SYSTEM_MAPPING_HEIGHT: 3300,

  MINIMAP_SCALE_FACTOR: 0.08,
  MINIMAP_POSITION_TOP: 12, // Default top position
  MINIMAP_POSITION_LEFT: 12, // This is now RIGHT position (distance from right edge)
  SEAT_OVERLAP_THRESHOLD: 0.1,
};

// Determine if minimap is positioned at the bottom (overlapping with FloorStatsBar)
export function isMinimapAtBottom(roomId) {
  const config = getRoomConfig(roomId);
  // If minimap top position is greater than 600px, it's likely at the bottom
  // You can adjust this threshold based on your layout
  return config.MINIMAP_POSITION_TOP > 600;
}
export const ROOM_WISE_CONFIG = {
  16101: {
    ZOOM_AFTER_SCALE: 1.95,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 100,
    MINIMAP_SCALE_FACTOR: 0.046,
    MINIMAP_POSITION_TOP: 690,
    MINIMAP_POSITION_LEFT: 1535,
    SEAT_OVERLAP_THRESHOLD: 0.5,
  },

  16301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 140,
    MINIMAP_SCALE_FACTOR: 0.06,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17201: {
    ZOOM_SEATS_SCALE: 1.05,
    ZOOM_AFTER_SCALE: 1.925,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 5,
    MINIMAP_SCALE_FACTOR: 0.065,
    MINIMAP_POSITION_TOP: 440,
    MINIMAP_POSITION_LEFT: 1645,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17202: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: false,
    SEAT_BOUNDS_MARGIN: 5,
    MINIMAP_SCALE_FACTOR: 0.046,
    MINIMAP_POSITION_TOP: 680,
    MINIMAP_POSITION_LEFT: 1540,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17101: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 90,
    MINIMAP_SCALE_FACTOR: 0.048,
    MINIMAP_POSITION_TOP: 670,
    MINIMAP_POSITION_LEFT: 1532,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 20,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 646,
    MINIMAP_POSITION_LEFT: 1505,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18201: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 200,
    MINIMAP_SCALE_FACTOR: 0.05,
    MINIMAP_POSITION_TOP: 653,
    MINIMAP_POSITION_LEFT: 1712,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18202: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 500,
    MINIMAP_SCALE_FACTOR: 0.048,
    MINIMAP_POSITION_TOP: 680,
    MINIMAP_POSITION_LEFT: 1516,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18101: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 95,
    MINIMAP_SCALE_FACTOR: 0.048,
    MINIMAP_POSITION_TOP: 670,
    MINIMAP_POSITION_LEFT: 1515,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18301: {
    ZOOM_AFTER_SCALE: 2,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 12,
    MINIMAP_SCALE_FACTOR: 0.048,
    MINIMAP_POSITION_TOP: 664,
    MINIMAP_POSITION_LEFT: 1725,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },
};

export function getRoomConfig(roomId) {
  const roomSpecificConfig = ROOM_WISE_CONFIG[roomId] || {};
  return {
    ...DEFAULT_VALUES,
    ...roomSpecificConfig,
  };
}
