export const DEFAULT_VALUES = {
  SEAT_FONT_SIZE_RATIO: 0.4,
  MINIMUM_SCALE_MULTIPLIER: 2.2,
  ZOOM_AFTER_SCALE: 1,
  USE_SEAT_BOUNDS: true,
  SEAT_BOUNDS_MARGIN: 50,
  MINIMAP_SCALE_FACTOR: 0.08,
  MINIMAP_POSITION_TOP: 10,
  MINIMAP_POSITION_LEFT: 10,
  SEAT_OVERLAP_THRESHOLD: 0.1,
};

export const ROOM_WISE_CONFIG = {
  16101: {
    SEAT_FONT_SIZE_RATIO: 0.42,
    MINIMUM_SCALE_MULTIPLIER: 2.4,
    ZOOM_AFTER_SCALE: 1.05,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 80,
    MINIMAP_SCALE_FACTOR: 0.09,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  16301: {
    SEAT_FONT_SIZE_RATIO: 0.48,
    MINIMUM_SCALE_MULTIPLIER: 2.1,
    ZOOM_AFTER_SCALE: 1,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 120,
    MINIMAP_SCALE_FACTOR: 0.085,
    MINIMAP_POSITION_TOP: 10,
    MINIMAP_POSITION_LEFT: 10,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17201: {
    SEAT_FONT_SIZE_RATIO: 0.46,
    MINIMUM_SCALE_MULTIPLIER: 2.2,
    ZOOM_AFTER_SCALE: 1.03,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 100,
    MINIMAP_SCALE_FACTOR: 0.08,
    MINIMAP_POSITION_TOP: 10,
    MINIMAP_POSITION_LEFT: 10,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17202: {
    SEAT_FONT_SIZE_RATIO: 0.38,
    MINIMUM_SCALE_MULTIPLIER: 2.5,
    ZOOM_AFTER_SCALE: 1.08,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 70,
    MINIMAP_SCALE_FACTOR: 0.075,
    MINIMAP_POSITION_TOP: 8,
    MINIMAP_POSITION_LEFT: 8,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17101: {
    SEAT_FONT_SIZE_RATIO: 0.41,
    MINIMUM_SCALE_MULTIPLIER: 2.3,
    ZOOM_AFTER_SCALE: 1.04,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 90,
    MINIMAP_SCALE_FACTOR: 0.085,
    MINIMAP_POSITION_TOP: 10,
    MINIMAP_POSITION_LEFT: 10,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  17301: {
    SEAT_FONT_SIZE_RATIO: 0.5,
    MINIMUM_SCALE_MULTIPLIER: 2.0,
    ZOOM_AFTER_SCALE: 1,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 110,
    MINIMAP_SCALE_FACTOR: 0.09,
    MINIMAP_POSITION_TOP: 12,
    MINIMAP_POSITION_LEFT: 12,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18201: {
    SEAT_FONT_SIZE_RATIO: 0.47,
    MINIMUM_SCALE_MULTIPLIER: 2.15,
    ZOOM_AFTER_SCALE: 1.02,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 95,
    MINIMAP_SCALE_FACTOR: 0.085,
    MINIMAP_POSITION_TOP: 10,
    MINIMAP_POSITION_LEFT: 10,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18202: {
    SEAT_FONT_SIZE_RATIO: 0.39,
    MINIMUM_SCALE_MULTIPLIER: 2.45,
    ZOOM_AFTER_SCALE: 1.06,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 75,
    MINIMAP_SCALE_FACTOR: 0.08,
    MINIMAP_POSITION_TOP: 9,
    MINIMAP_POSITION_LEFT: 9,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18101: {
    SEAT_FONT_SIZE_RATIO: 0.43,
    MINIMUM_SCALE_MULTIPLIER: 2.25,
    ZOOM_AFTER_SCALE: 1.03,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 85,
    MINIMAP_SCALE_FACTOR: 0.085,
    MINIMAP_POSITION_TOP: 10,
    MINIMAP_POSITION_LEFT: 10,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },

  18301: {
    SEAT_FONT_SIZE_RATIO: 0.49,
    MINIMUM_SCALE_MULTIPLIER: 2.05,
    ZOOM_AFTER_SCALE: 1,
    USE_SEAT_BOUNDS: true,
    SEAT_BOUNDS_MARGIN: 105,
    MINIMAP_SCALE_FACTOR: 0.09,
    MINIMAP_POSITION_TOP: 11,
    MINIMAP_POSITION_LEFT: 11,
    SEAT_OVERLAP_THRESHOLD: 0.1,
  },
};

export function getRoomConfig(roomId) {
  const roomSpecificConfig = ROOM_WISE_CONFIG[roomId] || {};
  return {
    ...DEFAULT_VALUES,
    ...roomSpecificConfig,
  };
}
